name: Android CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > admin/google-services.json

      - name: Build with Gradle
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          GOOGLE_WEB_CLIENT: ${{ secrets.GOOGLE_WEB_CLIENT }}
        run: ./gradlew build